# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

cache:
  - C:\RLibrary

install:
  ps: Bootstrap

environment:
  matrix:
  - R_VERSION: devel
    R_ARCH: x64
    #needed for data.table : Package data.table has compiled code, but no suitable compiler(s) were found
    USE_RTOOLS: true
    
  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64
    #needed for data.table :  Package data.table has compiled code, but no suitable compiler(s) were found
    USE_RTOOLS: true
    
  - R_VERSION: oldrel
    RTOOLS_VERSION: 35
    CRAN: http://cran.rstudio.com
    USE_RTOOLS: true
    
  - R_VERSION: oldrel
    RTOOLS_VERSION: 35
    CRAN: http://cran.rstudio.com
    USE_RTOOLS: true
    BIOC_USE_DEVEL: "FALSE"
    
  - R_VERSION: patched
    R_ARCH: x64
    GCC_PATH: mingw_64
    USE_RTOOLS: true

  - R_ARCH: x64
    GCC_PATH: mingw_64
    USE_RTOOLS: true
    
  - R_VERSION: release
    GCC_PATH: mingw_32
    USE_RTOOLS: true

  - R_VERSION: release
    R_ARCH: x64
    USE_RTOOLS: true

  - R_VERSION: patched
    USE_RTOOLS: true

  - R_ARCH: x64
    USE_RTOOLS: true

  - GCC_PATH: mingw_32
    USE_RTOOLS: true

#   - R_VERSION: 3.1.3
#     RTOOLS_VERSION: 32
#     CRAN: http://cran.rstudio.com

#   - R_VERSION: 3.1.0
#     RTOOLS_VERSION: 32
#     CRAN: http://cran.rstudio.com
#     PKGTYPE: source


# Adapt as necessary starting from here
# environment:
#   matrix:
#   - R_VERSION: devel
#     GCC_PATH: mingw_32
# 
# 
#   - R_VERSION: release
#     R_ARCH: x64
# 
#   - R_VERSION: stable
# 
#   - R_VERSION: patched
# 
#   - R_VERSION: oldrel
#     RTOOLS_VERSION: 33
#     CRAN: http://cran.rstudio.com
# 
#   - R_VERSION: 3.1.3
#     RTOOLS_VERSION: 32
#     CRAN: http://cran.rstudio.com
# 
#   - R_VERSION: 3.1.0
#     RTOOLS_VERSION: 32
#     CRAN: http://cran.rstudio.com
#     PKGTYPE: source
    

  
build_script:
  - set _R_CHECK_FORCE_SUGGESTS_=false
  - travis-tool.sh install_deps
#before  - ./travis-tool.sh install_github Bioconductor-mirror/zlibbioc
#  - ./travis-tool.sh install_github Bioconductor-mirror/rhdf5
#after 
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_github Rdatatable/data.table
  

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
